"""followers

Revision ID: 96edf42fb446
Revises: 6b3a08ec4794
Create Date: 2021-10-05 18:44:30.928576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96edf42fb446'
down_revision = '6b3a08ec4794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
